FROM busybox

RUN busybox echo "123" | grep "123"

RUN busybox echo "124" | grep "124"

RUN busybox echo "123" | grep "123"

RUN busybox echo "123" | grep "123"

RUN busybox echo "123" | grep "123"

CMD ["echo" "Hello World!"]
