on:
  push:
    branches:
      - master
      - stage
      - prod

jobs:
  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
#       BUILDKIT_INLINE_CACHE: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Unit Tests
      run: |
       chmod +x run.sh
        ./run.sh
    - name: API Tests
      run: |
       chmod +x run.sh
        ./run.sh

