on:
  push:
    branches:
      - master
      - stage
      - prod
  pull_request:

jobs:
  env1:
    name: ENV1
    runs-on: ubuntu-latest
    environment:
      name: test
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
#       BUILDKIT_INLINE_CACHE: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: ENV1
      run: |
        ./run.sh

  env2:
    name: ENV2
    runs-on: ubuntu-latest
    environment:
      name: env2
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
#       BUILDKIT_INLINE_CACHE: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: ENV2
      environment: ENV2
      run: |
        ./run.sh

