on:
  push:
    branches:
      - master
      - stage
      - prod
  pull_request:

jobs:
  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
#       BUILDKIT_INLINE_CACHE: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: ENV1
      run: |
        ./run.sh
      environment: test
    - name: ENV2
      environment: ENV2
      run: |
        ./run.sh

