on:
  push:

jobs:
  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
#       BUILDKIT_INLINE_CACHE: 1
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT1 }}
        logout: true
    - name: Checkout
      uses: actions/checkout@v2
    - name: Unit Tests
      run: |
       chmod +x run.sh
        ./run.sh

